version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:9.0.0 
    steps:
      - checkout 
      - run: npm install
      - run: npm run lint
      - run: npm test

workflows:
    version: 2
    build-and-test:
      jobs:
        - build-and-test